- k8s/apps.go
- k8s/k8s.go
- k8s/networks.go
TERESAK8S_DEFAULTSERVICETYPE variable
> Get default kubernetes service type from the environment

- k8s/apps.go
- only consider running pods
- avoid a race condition when accessing a pointer to a range variable inside
a goroutine; this was causing the selection of the wrong pods
- simplify code by avoiding bufio
- don't leak fds
> Fixes for the apps logs endpoint

- README.md
- k8s/deployments.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/153)
> Set revision history limit per app

- README.md
- add tips to deploy python, nodejs and golang application
- explain about procfile
- explain about $PORT (env var)
- doc healthcheck based on teresa.yaml
- doc rolling update deployment based on teresa.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/155)
> some improves in README

- k8s/apps.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/162)
> fix LoadBalancer information for cluster on gcp

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/163)
> add reference to `hello-teresa` repo and remove duplicated docs

- CHANGELOG.md
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/159)
> use API to generate user password instead of python script

- CHANGELOG.md
- models/storage/models.go
useful for tests with minikube
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/156)
> use `TERESADB_DATABASE` environment to define location of teresa.sqlite

- CHANGELOG.md
- k8s/k8s_constants.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/167)
> change slugbuilder and slugrunner image location

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/171)
> Fix install docs by adding section on secrets

- CHANGELOG.md
- README.md
- handlers/auth.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/173)
> get current namespace from an environment variable instead of a constant

- cmd/client/CHANGELOG.md
- cmd/client/cmd/deploy.go
Hopefully fixes #178.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/179)
> Fix the deploy archive building with .teresaignore on Windows

- cmd/client/cmd/app.go
- cmd/client/cmd/deploy.go
- cmd/client/cmd/root.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/181)
> Typo, initialism and remove of an unnecessary return statement 

- .travis.yml
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/194)
> add travis stuff

- pkg/server/database/database_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/191)
> add simple test in database connection factory

- pkg/server/user/errors.go
- pkg/server/user/user.go
- pkg/server/user/user_test.go
- pkg/server/validations/validations.go
- pkg/server/validations/validations_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/200)
> add email validation on user create

- pkg/server/cmd/run.go
- pkg/server/k8s/errors.go
- pkg/server/k8s/k8s.go
- pkg/server/k8s/k8s_test.go
- pkg/server/k8s/unversioned.go
- pkg/server/server.go
- pkg/server/storage/errors.go
- pkg/server/storage/s3.go
- pkg/server/storage/s3_test.go
- pkg/server/storage/storage.go
- pkg/server/storage/storage_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/202)
> Add k8s client and storage grpc server options

- pkg/server/storage/fake.go
- pkg/server/storage/fake_test.go
- pkg/server/storage/storage.go
For testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/204)
> Add fake storage implementation

- cmd/client/cmd/app.go
- cmd/client/cmd/login_cluster.go
- cmd/client/cmd/root.go
- cmd/client/cmd/team.go
- cmd/client/cmd/user.go
- cmd/client/connection/connection.go
- pkg/client/client.go
- pkg/server/cmd/run.go
- pkg/server/server.go
--tlsinsecure for the client and --notls for both. It's important to be able to disable TLS for the development environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/210)
> Add TLS options to the server and client

- cmd/client/cmd/app.go
- cmd/client/cmd/config.go
- cmd/client/cmd/deploy.go
- cmd/client/cmd/login_cluster.go
- cmd/client/cmd/team.go
- cmd/client/cmd/user.go
- pkg/client/errors.go
- pkg/client/errors_test.go
- pkg/server/cmd/user.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/216)
> add func `PrintErrorAndExit` and uses it to print error msgs on the client

- cmd/client/cmd/app.go
- pkg/server/deploy/deploy.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/222)
> miscellaneous improvements on client

- pkg/server/cmd/version.go
- pkg/version/version.go
The next PR's will add a ldflags based versioning scheme.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/225)
> Add server version command

- cmd/client/cmd/constants.go
- cmd/client/cmd/version.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/228)
> Unify server and client versions

- Dockerfile
- Makefile
No more hardcoded version numbers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/229)
> Implement versioning scheme based on ldflags

- Godeps/Godeps.json
- pkg/server/healthcheck/server.go
- pkg/server/healthcheck/server_test.go
- pkg/server/k8s/client.go
- pkg/server/k8s/k8s.go
- pkg/server/server.go
- vendor/github.com/soheilhy/cmux/.gitignore
- vendor/github.com/soheilhy/cmux/.travis.yml
- vendor/github.com/soheilhy/cmux/CONTRIBUTORS
- vendor/github.com/soheilhy/cmux/LICENSE
- vendor/github.com/soheilhy/cmux/README.md
- vendor/github.com/soheilhy/cmux/buffer.go
- vendor/github.com/soheilhy/cmux/cmux.go
- vendor/github.com/soheilhy/cmux/doc.go
- vendor/github.com/soheilhy/cmux/matchers.go
- vendor/github.com/soheilhy/cmux/patricia.go
Useful feature to monitoring teresa and k8s health outside of cluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/230)
> expose a simple health check on a http server

- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/232)
> [server] upgrade golang version to 1.8

- pkg/server/server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/234)
> TLS packets go to the grpc listener

- cmd/client/cmd/root.go
Fixes, better style and document new flags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/235)
> Fix teresa client root documentation

- pkg/server/server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/238)
> only match TLS connection on server if tls is turned on

- pkg/server/team/team.go
- pkg/server/team/team_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/237)
> Return list of users in `team list` command for a non admin users

- pkg/goutil/channels.go
- pkg/goutil/channels_test.go
- pkg/server/app/handlers.go
- pkg/server/deploy/handlers.go
By always sending a report if there are logs or not.
Also useful with --follow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/239)
> Fix app log lost connections

- pkg/server/app/app.go
- pkg/server/app/app_test.go
- pkg/server/app/errors.go
- pkg/server/k8s/client.go
Also emit better error messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/241)
> Make create app delete the namespace on errors

- cmd/client/cmd/config.go
So the user doesn't need to append the default grpc port to the server name. Also update the documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/242)
> Add port to the client set-cluster command

- cmd/client/cmd/app.go
- cmd/client/cmd/completion.go
- cmd/client/cmd/root.go
- cmd/client/cmd/teresaclient.go
Code removed was unused/broken/unneeded or simply added noise
to the error messages. Some error checks were removed from code 
that soon will be deleted for compiling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/243)
> Major client root cmd cleanup

- pkg/client/client.go
This way we get clear messages on connection errors, for instance:
`Error connecting to server: myserver:50051`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/245)
> Add client grpc dial timeout

- cmd/client/cmd/app.go
- cmd/client/cmd/config.go
- cmd/client/cmd/create.go
- cmd/client/cmd/delete.go
- cmd/client/cmd/login_cluster.go
- better style
- fix cpu units (Gi -> m)
- env-set and env-unset docs are now acessible
- delete and create only operate on users
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/246)
> Documentation fixes

- pkg/client/password.go
- pkg/client/password_test.go
Better security and to avoid mistakes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/248)
> Add min password length to the set-password command

- Makefile
- fixes for the new project structure
- better style
- better targets
- doc fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/252)
> Makefile overhaul

- pkg/server/k8s/client.go
this change will help us with concurrency
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/250)
> build a k8s client per operation instead of using the same

- .travis.yml
To check which test failed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/254)
> add `verbose` flag when run tests on travis build

- .tests-run.sh
- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/257)
> add codecov integration

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/260)
> runs travis build only on golang 1.8 and tip

- helm/chart/teresa/templates/service.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/262)
> fix(helm/service) app selector

- helm/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/263)
> fix typo in helm readme

- helm/README.md
- helm/chart/teresa/templates/deployment.yaml
- helm/chart/teresa/values.yaml
Specific stuff to works fine with minio as slug storage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/264)
> add storage type and s3 endpoint on helm chart

- pkg/client/cmd/root.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/266)
> Add missing port parameter to the client root doc

- pkg/server/app/app.go
- pkg/server/app/app_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/267)
> Fix app last user by using the email instead of name

- CHANGELOG.md
- pkg/client/cmd/user.go
In a way that we can put it back easily.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/270)
> Remove client admin flag

- pkg/server/deploy/deploy.go
A little issue that I noticed when I ate my own dog food.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/269)
> streaming a msg if deploy failed to upload the tarball

- helm/chart/teresa/Chart.yaml
- helm/chart/teresa/templates/deployment.yaml
sorry my bad!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/271)
> fix deployment template on helm chart

- README.md
- helm/README.md
Fix base64 command on Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/272)
> Fix README section on installation

- .ci-docker.sh
- .travis.yml
Before a real test, we need to set those env-vars on Travis repo configs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/268)
> [Proposal] add a script to build and up the last tag of project to Docker hub

- CHANGELOG.md
- helm/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/274)
> bumpversion v0.5.0

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/275)
> fix travis script to build a docker image from a git tag

- .helm-test.sh
- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/273)
> add helm lint to travis

- .ci-docker.sh
- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/277)
> create another build stage to generate docker image

- helm/chart/teresa/Chart.yaml
- helm/chart/teresa/templates/service.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/279)
> Use default grpc port on helm service

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/283)
> fix missing changelog entries

- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/286)
> add helm lint and update to makefile

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/287)
> fix travisci stage build

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/288)
> Add FAQ to the README

- CHANGELOG.md
- pkg/client/cmd/app.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/289)
> change default max-cpu flag to 200m in command create app

- CHANGELOG.md
- pkg/server/middlewares.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/290)
> server doesn't log request content on log interceptor if the route is Login

- pkg/server/k8s/client.go
On the presence of pending pods for instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/292)
> Fix nil pointer dereference on app info command

- helm/README.md
- helm/chart/teresa/Chart.yaml
- helm/chart/teresa/templates/deployment.yaml
- helm/chart/teresa/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/294)
> add cpu and memory limit envs

- HomebrewFormula/teresa.rb
- README.md
I will try to move from old repository using this strategy. https://docs.brew.sh/Migrating-A-Formula-To-A-Tap.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/298)
> move homebrew formula to oficial repository

- helm/chart/teresa/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/299)
> feat(helm) bump teresa version

- CHANGELOG.md
- pkg/server/cmd/run.go
- pkg/server/middlewares.go
- pkg/server/server.go
For now only prints the stack trace on every panic/recover.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/297)
> Add --debug flag to the server

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/295)
> fix travis after_success scope

- helm/README.md
- helm/chart/teresa/Chart.yaml
- helm/chart/teresa/templates/deployment.yaml
- helm/chart/teresa/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/301)
> add --debug option to helm chart

- CHANGELOG.md
- pkg/client/cmd/app.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/303)
> Make cmds 'env-set' and 'env-unset' show the current cluster

- CHANGELOG.md
- pkg/server/k8s/client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/306)
> Fix restart count on app info output

- CHANGELOG.md
- pkg/client/cmd/deploy.go
For instance reject missing app parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/304)
> Validate client deploy command parameters

- pkg/client/cmd/app.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/305)
> use PrintErrorAndExit on setEnv and unsetEnv

- CHANGELOG.md
- pkg/client/cmd/deploy.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/307)
> Fix hanging deploys when the app dir doesn't exist

- CHANGELOG.md
- pkg/client/cmd/app.go
- pkg/client/cmd/constants.go
- pkg/client/cmd/deploy.go
- pkg/client/cmd/login_cluster.go
- pkg/client/cmd/root.go
- pkg/client/cmd/team.go
- pkg/client/cmd/user.go
- pkg/client/config.go
- pkg/client/config_test.go
- pkg/client/connection/connection.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/308)
> add --cluster to the client

- .ci-docker.sh
- Makefile
also:
- made the CI script use the makefiles targets to generate and push the
image
- added the prefix `docker-` on docker makefile targets
- set `TERESA_SECRETS_PRIVATE_KEY` and `TERESA_SECRETS_PUBLIC_KEY` to
fake keys by default
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/309)
> fixed `docker run` command

- .ci-docker.sh
Until we change to use makefile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/310)
> revert .ci-docker.sh script

- helm/chart/teresa/Chart.yaml
- helm/chart/teresa/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/313)
> bumped teresa version on helm

- README.md
- fix question about the deploy command
- add questions about teresa.yaml per process types and draining connections.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/315)
> Update the FAQ

- pkg/server/app/fake_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/318)
> add test to fakeOps.SetAutoscale

- CHANGELOG.md
- pkg/client/cmd/app.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/320)
> don't print pod without status on app info

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/322)
> fix homebrew repo

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/328)
> add release, software license and go report card to readme

- helm/chart/teresa/templates/NOTES.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/326)
> add helm notes

- pkg/client/cmd/app.go
- pkg/server/app/app.go
- pkg/server/app/app_test.go
- pkg/server/app/fake.go
- pkg/server/deploy/build_test.go
- pkg/server/k8s/client.go
- pkg/server/k8s/converters.go
- pkg/server/k8s/converters_test.go
- pkg/server/team/fake_test.go
- pkg/server/team/handlers_test.go
run `gofmt -s -w pkg`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/330)
> run gofmt -s

- pkg/client/cmd/deploy.go
fix ineffassign issue in go report card
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/332)
> remove unused assignment

- pkg/server/app/app_test.go
- pkg/server/app/fake_test.go
- pkg/server/app/models_test.go
- pkg/server/deploy/responses_test.go
- pkg/server/k8s/converters_test.go
fix go_vet issues
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/334)
> fix typos in tests

- CHANGELOG.md
- pkg/client/cmd/app.go
- pkg/client/sort.go
- pkg/client/sort_test.go
fixes #336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/337)
> sort envs in app info

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/338)
> get build status from master branch

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/339)
> artifacts -> docker images on README

- README.md
Actually, those are "build artifacts".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/341)
> docker images -> artifacts on README

- CHANGELOG.md
- helm/chart/teresa/Chart.yaml
- helm/chart/teresa/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/342)
> bumpversion v0.8.0

- CHANGELOG.md
- pkg/server/deploy/handlers.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/349)
> Upgrade default slugbuilder version to v3.0.0

- helm/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/353)
> update helm readme

- pkg/client/cmd/constants.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/357)
> remove unused vars

- pkg/server/k8s/client.go
- pkg/server/k8s/converters.go
- pkg/server/k8s/errors.go
- pkg/server/middlewares_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/359)
> small code improvements according to `megacheck`

- CHANGELOG.md
- helm/chart/teresa/Chart.yaml
- helm/chart/teresa/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/361)
> bumpversion v0.9.0

- helm/chart/teresa/templates/deployment.yaml
💅
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/363)
> improve helm args

- CHANGELOG.md
- pkg/client/cmd/deploy.go
fixes #344 
fixes #345
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/355)
> improve deploy list output

- CHANGELOG.md
- pkg/client/cmd/app.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/365)
> Fix app info pod count by ignoring pods without state

- pkg/server/app/fake_test.go
🤦‍♂️
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/367)
> fix a simple test format

- pkg/server/k8s/converters_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/368)
> fix little govet issue on converters test

- CHANGELOG.md
- helm/chart/teresa/Chart.yaml
- helm/chart/teresa/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/369)
> bumpversion v0.10.0

- CHANGELOG.md
- pkg/server/k8s/client.go
fix #371 related #350
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/375)
> Don't return error on `app info` command if the app doesn't have HPA

- CHANGELOG.md
- helm/README.md
- helm/chart/teresa/templates/clusterrolebinding.yaml
- helm/chart/teresa/templates/deployment.yaml
- helm/chart/teresa/templates/serviceaccount.yaml
- helm/chart/teresa/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/364)
> add rbac support in helm chart

- CHANGELOG.md
- helm/chart/teresa/Chart.yaml
- helm/chart/teresa/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/378)
> bumbversion v0.11.0

- CHANGELOG.md
- pkg/client/cmd/app.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/380)
> log alias to app logs command and shorthand to follow and lines

- CHANGELOG.md
- pkg/server/app/app.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/381)
> Fix env vars being set or unset on deploy update errors

- CHANGELOG.md
- pkg/server/server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/382)
> Fix typo on server pkg

- pkg/server/app/app.go
Fix commit 4913946fff48a27a529507e07968122752d719b9.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/384)
> Fix env commands by ignoring not found errors

- CHANGELOG.md
- pkg/server/deploy/deploy.go
- pkg/server/deploy/deploy_test.go
- pkg/server/deploy/fake.go
- pkg/server/deploy/handlers.go
Errors from the deploy goroutine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/386)
> Fix server not returning all deploy errors to the client

- CHANGELOG.md
- pkg/server/k8s/converters.go
- pkg/server/k8s/converters_test.go
> Don't use the default service account on builds and deploys

- CHANGELOG.md
- Dockerfile
Refactoring Dockerfile for image resize.
> Bc refactor docker

- pkg/server/cmd/run.go
- pkg/server/k8s/client.go
- pkg/server/k8s/errors.go
- pkg/server/k8s/k8s.go
- pkg/server/server.go
Golang is smart enough to infer the interfaces on business packages.
> Remove unnecessary interfaces of k8s pkg

- CHANGELOG.md
With #416 we'll upgrade golang version of both (client and server) 🚀
> Add note on changelog about upgrade of golang version of client

- .goreleaser.yml
to fix bug on generate client binary
> Change ldflags on .goreleaser config

- pkg/server/app/app.go
- pkg/server/app/app_test.go
- pkg/server/team/fake.go
- pkg/server/team/fake_test.go
- pkg/server/team/team.go
- pkg/server/team/team_test.go
> Add method team.HasUser

- CHANGELOG.md
- pkg/server/cmd/secrets.go
- pkg/server/k8s/client.go
To replace the storage secret for all apps.
> Add replace-storage-secret server admin command

- CHANGELOG.md
- pkg/server/deploy/deploy.go
- pkg/server/deploy/handlers.go
- pkg/server/exec/exec.go
- pkg/server/k8s/converters.go
- pkg/server/k8s/converters_test.go
- pkg/server/server.go
- pkg/server/slug/slug.go
- pkg/server/spec/container.go
- pkg/server/spec/deploy.go
- pkg/server/spec/deploy_test.go
- pkg/server/spec/pod.go
- pkg/server/spec/pod_test.go
So it doesn't mount the storage keys anymore.
> Make the slugrunner use an init container to download the app code

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
> Add CONTRIBUTING and related FAQ entry

- .travis.yml
> Create goreleaser script on a temporary dir in travis script

- CHANGELOG.md
- pkg/server/app/app.go
- pkg/server/app/app_test.go
- pkg/server/cmd/secrets.go
- pkg/server/k8s/client.go
This change will help me with "secrets support" feature
> Refactor create or update secret

- pkg/server/deploy/deploy.go
- pkg/server/deploy/deploy_test.go
- pkg/server/k8s/client.go
- pkg/server/spec/deploy.go
- pkg/server/spec/deploy_test.go
> Create configMap to nginx deploy, and only deploy nginx if nginx.conf

- CHANGELOG.md
- pkg/server/spec/container.go
This change fix some issues on get slug with minion as storage backend
> Add storage.Storage PodEnvVars on spec of InitContainer

- pkg/server/cloudprovider/cloudprovider.go
- pkg/server/cloudprovider/cloudprovider_test.go
- pkg/server/cloudprovider/errors.go
- pkg/server/cloudprovider/fallback.go
This change allows Teresa to up in any k8s cluster on any cloudprovider
no matter if is not well know provider
> Add a `fallback` struct for pkg `cloudprovider`

- CHANGELOG.md
- Godeps/Godeps.json
- pkg/client/tar/tar.go
- pkg/client/tar/tar_test.go
- vendor/github.com/sabhiram/go-gitignore/.gitignore
- vendor/github.com/sabhiram/go-gitignore/.travis.yml
- vendor/github.com/sabhiram/go-gitignore/LICENSE
- vendor/github.com/sabhiram/go-gitignore/README.md
- vendor/github.com/sabhiram/go-gitignore/ignore.go
Fixes #451
`go-gitignore` works fine, but doesn't follow semver :/ I already open an issue ask for tags.
I'll try some tests (compiling client) before merge.
> Add `go-gitignore` to generate tar with `.teresaignore`

- CHANGELOG.md
- helm/chart/teresa/Chart.yaml
- helm/chart/teresa/values.yaml
⚠️ Tag and Release already generated
> Bump Version to v0.18.0

- CHANGELOG.md
- README.md
- pkg/server/spec/container.go
- pkg/server/spec/deploy.go
- pkg/server/spec/pod.go
- pkg/server/spec/pod_test.go
This change allows nginx to serves application static content
(depends on https://github.com/luizalabs/slugrunner/pull/6)
> Add a volume in pods with nginx sidecar to share fs

- CHANGELOG.md
- README.md
- pkg/server/deploy/handlers.go
Also add a FAQ entry with an example dynamic configuration.
> Change default nginx image to nginx:1.13-alpine-perl

- CHANGELOG.md
- pkg/server/deploy/deploy.go
- pkg/server/deploy/deploy_test.go
- pkg/server/k8s/client.go
- pkg/server/k8s/converters.go
- pkg/server/k8s/converters_test.go
> Make deploy rollback update the app env vars

- FAQ.md
- README.md
- add kubernetes version requirement
- fix typos and better style
- split FAQ into file
- update and add new entries to the FAQ
> Improve the README and FAQ

- .gitignore
- pkg/server/build/build.go
- pkg/server/build/build_test.go
- pkg/server/build/errors.go
- pkg/server/build/fake.go
- pkg/server/build/fake_test.go
- pkg/server/deploy/deploy.go
- pkg/server/deploy/deploy_test.go
- pkg/server/deploy/errors.go
- pkg/server/k8s/client.go
- pkg/server/k8s/converters.go
- pkg/server/k8s/converters_test.go
- pkg/server/server.go
- pkg/server/spec/deploy.go
- pkg/server/spec/pod.go
- pkg/server/spec/service.go
- pkg/server/spec/service_test.go
- pkg/server/test/fake.go
This PR is the first part of N about `build` feature.
> Add build pkg and some generalizations

- pkg/server/cloudprovider/aws.go
- pkg/server/k8s/client.go
- pkg/server/k8s/converters.go
- pkg/server/k8s/converters_test.go
- pkg/server/service/fake.go
- pkg/server/service/responses.go
- pkg/server/service/responses_test.go
- pkg/server/service/service.go
- pkg/server/spec/service.go
- pkg/server/spec/service_test.go
So we can unify port translation.
> Move service.ServicePort struct to the spec package

- CHANGELOG.md
- pkg/server/deploy/deploy.go
- pkg/server/deploy/deploy_test.go
- pkg/server/k8s/client.go
- pkg/server/k8s/converters.go
- pkg/server/k8s/converters_test.go
- pkg/server/service/fake.go
- pkg/server/service/service.go
- pkg/server/service/service_test.go
- pkg/server/spec/deploy.go
- pkg/server/spec/service.go
- pkg/server/spec/service_test.go
It's a requirement for a istio based service mesh.
> Name service ports with the protocol

- pkg/server/build/build.go
- pkg/server/build/build_test.go
- pkg/server/build/fake.go
- pkg/server/deploy/deploy.go
- pkg/server/deploy/deploy_test.go
- pkg/server/k8s/client.go
- pkg/server/k8s/converters.go
- pkg/server/server.go
This PR is the second part of N about build feature.
> Add method build.Create to create (and run) a new build

- CHANGELOG.md
- pkg/server/cloudprovider/cloudprovider.go
- pkg/server/cloudprovider/cloudprovider_test.go
- pkg/server/server.go
instead of return an error and crash the server
> Return fallback operations for unknown cloud providers

- CHANGELOG.md
- pkg/server/cloudprovider/aws.go
- pkg/server/cloudprovider/aws_test.go
- pkg/server/cloudprovider/cloudprovider.go
- pkg/server/cloudprovider/fake.go
> Fix ssl enablement with ingress on aws

- CHANGELOG.md
- pkg/server/deploy/handlers.go
slugbuilder to v3.4.0
slugrunner to v3.2.0
> Bump the default slugs version

- CHANGELOG.md
- pkg/goutil/channels.go
- pkg/goutil/channels_test.go
- pkg/server/app/handlers.go
- pkg/server/build/handlers.go
- pkg/server/deploy/handlers.go
- pkg/server/exec/handlers.go
Also refactor the goutil package.
> Fix lack of error handling when streaming from readers

- CHANGELOG.md
- pkg/client/cmd/app.go
- pkg/client/cmd/validators.go
- pkg/client/cmd/validators_test.go
> Add client limits validation on app creation

- CHANGELOG.md
- pkg/server/k8s/client.go
Caused by an index out of range error.
> Fix panic when monitoring the rolling update

- CHANGELOG.md
- pkg/server/spec/container.go
So it doesn't get the namespace limits.
> Add limits to the nginx container

- FAQ.md
Gotcha! depends on -> luizalabs/slugrunner#10
> Add instruction on FAQ about "how to run an app locally"

- README.md
- helm/README.md
- helm/chart/teresa/templates/NOTES.txt
Thank you @dereke to show us this bugs
> Improve documentation and fix wrong notes on helm chart

- Makefile
It calls build-server and build-client.
> Add the makefile target build-all

- pkg/server/user/user.go
- pkg/server/validation/email.go
- pkg/server/validation/email_test.go
- pkg/server/validations/validations.go
- better names
- simpler implementation
> Refactor the server validations package

- CHANGELOG.md
- pkg/server/build/build.go
- pkg/server/deploy/deploy.go
- pkg/server/exec/exec.go
- pkg/server/spec/build.go
- pkg/server/spec/build_test.go
- pkg/server/spec/container.go
- pkg/server/spec/container_test.go
- pkg/server/spec/cronjob.go
- pkg/server/spec/cronjob_test.go
- pkg/server/spec/deploy.go
- pkg/server/spec/deploy_test.go
- pkg/server/spec/initcontainer.go
- pkg/server/spec/initcontainer_test.go
- pkg/server/spec/nginx.go
- pkg/server/spec/nginx_test.go
- pkg/server/spec/pod.go
- pkg/server/spec/pod_test.go
- pkg/server/spec/runner.go
- pkg/server/spec/runner_test.go
This change will facilitate futures features like cloud-sql side-car, volumes, etc.
> Refactor spec pkg to use DP Builder

- CHANGELOG.md
- pkg/server/k8s/converters.go
- pkg/server/k8s/converters_test.go
So the app can use an Unix socket file to communicate with nginx.
> Change healthcheck port back to the nginx one

- CHANGELOG.md
- pkg/server/app/app.go
- pkg/server/cloudprovider/aws.go
- pkg/server/cloudprovider/aws_test.go
- pkg/server/cloudprovider/cloudprovider.go
- pkg/server/cloudprovider/errors.go
- pkg/server/cloudprovider/fake.go
- pkg/server/service/fake.go
- pkg/server/service/service.go
- pkg/server/service/service_test.go
Don't use the virtual host or the server setting.
> Fix app ingress detection

- CHANGELOG.md
- helm/chart/teresa/Chart.yaml
- helm/chart/teresa/values.yaml
:man_facepalming: 
I forgot to add changelog to my change. I also realized that the Bump to v0.29.0 had the incorrect date.
> Bumpversion to v0.30.0

- pkg/client/cmd/app.go
- vendor/k8s.io/api/core/v1/types.go
Just fixed the word 'secert' to 'secret'
> Fixed message typo

- .ci-docker.sh
- CONTRIBUTING.md
- FAQ.md
- pkg/client/cmd/app.go
- pkg/client/cmd/build.go
- pkg/client/cmd/config.go
- pkg/client/cmd/deploy.go
- pkg/client/errors.go
> Fixed some typos

- CHANGELOG.md
- pkg/server/deploy/handlers.go
> Update default nginx image to support lua scripts

- CHANGELOG.md
- pkg/server/deploy/deploy.go
- pkg/server/deploy/deploy_test.go
- pkg/server/k8s/client.go
- pkg/server/validation/envvars_test.go
> Do not create ingress for apps without vHost

- CHANGELOG.md
- pkg/server/cloudprovider/gce.go
- pkg/server/cloudprovider/gce_test.go
- pkg/server/deploy/deploy.go
- pkg/server/deploy/deploy_test.go
This PR checks if the app has a Teresa managed ingress before trying to reserve a static IP.
Fixes #634
> Checks if app already has ingress before trying to reserve a static IP

- README.md
This Pull Request does two things:
- It moves the client installation section to the top, since its the most common way of using `teresa`
- It adds the Download section to the Client Installation, to lighten how to get the latest release
The download installation tutorial was given to me by Renan Augusto (idk his github account), so this Pull Request was only possible because of him :blush:
> Readme: make client installation clearer
