luizalabs/teresa

k8s/deployments.go
The reason is that the app's number is not synced with the hpa
and a deployment may cause a huge decrease on the number of
running pods and consequently service unavailability.
=> Don't set the number of replicas on new deployments

CHANGELOG.md, k8s/deployments.go
Deploy is a streaming operation and we need the connection open even with the presence of firewalls or load balancers that have idle timeouts. As we don't control go-swagger autogenerated server we send a "ping" to the client every 30 seconds by default (this value may be changed using the TERESADEPLOY_KEEPALIVE_TIMEOUT env var).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/174)
=> Fix deploy timeouts

CHANGELOG.md, k8s/users.go
Before this fix a user would get access only to apps from one of its teams.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/186)
=> Fix multi teams tokens by avoiding pointer to range var

pkg/client/errors.go, pkg/client/errors_test.go, pkg/server/auth/errors.go
This way the client always return a clean and specific error message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/195)
=> Use grpc status for errors

Dockerfile, cmd/server/main.go, pkg/server/cmd/db.go, pkg/server/cmd/root.go, pkg/server/cmd/run.go, pkg/server/cmd/user.go
Use this command to avoid raw mysql inserts.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/198)
=> Add command `create-super-user` in server command line interface

pkg/server/deploy/deploy.go, pkg/server/deploy/deploy_test.go, pkg/server/deploy/errors.go, pkg/server/deploy/handlers.go, pkg/server/k8s/client.go, pkg/server/middlewares.go, pkg/server/middlewares_test.go, pkg/server/server.go, pkg/server/teresa_errors/errors.go, pkg/server/teresa_errors/errors_test.go
Only applied for `Deploy` pkg.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/214)
=> [Proposal] Standardize errors and Logs with Middlewares

pkg/server/app/app.go, pkg/server/app/app_test.go, pkg/server/app/errors.go, pkg/server/app/fake.go, pkg/server/app/fake_test.go, pkg/server/app/handlers.go, pkg/server/app/handlers_test.go, pkg/server/k8s/errors.go, pkg/server/team/team.go, pkg/server/teresa_errors/errors.go, pkg/server/teresa_errors/errors_test.go, pkg/server/user/user.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/218)
=> standardize errors and logs of server pkg

pkg/server/k8s/client.go, pkg/server/k8s/k8s.go
That timeout broke api streams (app log and deploy)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/224)
=> remove timeout from k8s client

cmd/client/cmd/app.go, cmd/client/cmd/config.go, cmd/client/cmd/deploy.go, cmd/client/cmd/login_cluster.go, cmd/client/cmd/root.go, cmd/client/cmd/team.go, cmd/client/cmd/user.go, cmd/client/connection/connection.go, pkg/client/client.go, pkg/client/config.go, pkg/client/testdata/validConfigFile.yaml, pkg/server/cmd/run.go
To simplify the up and run process for new users, this PR changes the default behavior of server and client to **don't** use TLS by default.
Today we need to use the flag `--notls` for each command. With this PR you only need to use the flag `--tls` when you use the `set-cluster`  command if you want to use TLS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/227)
=> No TLS by default

pkg/server/deploy/build.go, pkg/server/deploy/build_test.go, pkg/server/deploy/deploy.go, pkg/server/deploy/deploy_test.go, pkg/server/deploy/handlers.go
We should be able to change the images fast (for security patches for instance) and without a new deploy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/231)
=> [Proposal] Make slug images configurable by env vars

pkg/server/deploy/build.go, pkg/server/storage/fake.go, pkg/server/storage/fake_test.go, pkg/server/storage/minio.go, pkg/server/storage/minio_test.go, pkg/server/storage/s3.go, pkg/server/storage/s3_test.go, pkg/server/storage/storage.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/236)
=> Suport to `Minio` as slug storage backend

pkg/server/slug/slug.go
Because with a wrong python-path the slugbuilder doesn't works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/240)
=> add `PYTHONPATH` as a protected env variable

Dockerfile
- use default grpc port
- use ENTRYPOINT, which is more flexible: we can vary the command
parameters without rebuilding the image
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/249)
=> Better Dockerfile

pkg/server/deploy/handlers.go
Those versions fix the support for minio as slug storage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/256)
=> update default versions of slugbuilder and slugrunner

pkg/client/cmd/user.go, pkg/client/password.go, pkg/client/password_test.go
To prevent access troubles for users already saved with a weak password length.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa-api/261)
=> only check password length in `set-password` command

pkg/client/cmd/app.go
This is for avoiding problem with kube-dns.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/282)
=> limit the size of app name

pkg/client/cmd/app.go, pkg/client/cmd/deploy.go
for commands: `env-set`, `env-unset` and `deploy`.
Without those changes, the client will show a cluster name in the command message but will perform the command in another cluster, f.ex:
```shell
$ teresa app env-unset FOO --cluster production --app awesome-app
Unsetting env vars and restarting "awesome-app" on "staging"...
FOO
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/311)
=> use the cluster informed by the user to shows command advice

pkg/client/cmd/deploy.go
We've updated the deploy command to match the pattern we've been using across the whole app, which is: `entity action`.
So to inform the users of the new cli signature, I've added a tiny help text redirecting them to the new command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/340)
=> add help while running the deprecated `teresa deploy`

CHANGELOG.md, pkg/client/cmd/login_cluster.go, pkg/client/config.go, pkg/client/config_test.go
The `teresa login` ignore the `--cluster` flag on saving token to config file, this pr fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/348)
=> check --cluster flag when saving token to config file in teresa login 

CHANGELOG.md, pkg/server/k8s/client.go
Others layers  (converter, handler, cli, etc) already deal with `nil` autoscale information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/350)
=> handle hpa not found (as normal behavior) on app info

.gitignore, CHANGELOG.md, helm/README.md, helm/chart/teresa/requirements.lock, helm/chart/teresa/requirements.yaml, helm/chart/teresa/templates/deployment.yaml, helm/chart/teresa/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luizalabs/teresa/314)
=> [HELM] use minio on teresa chart

CHANGELOG.md, pkg/client/cmd/deploy.go, pkg/client/tar/tar.go
Use "/" as tar path separator as this is the portable way.
=> Fix teresaignore on Windows

CHANGELOG.md, pkg/client/cmd/deploy.go
Do it before openning a connection to the server and remove the file before exiting.
=> Fix tar file creation on deploys

CHANGELOG.md, pkg/server/database/database.go
Env `TERESA_DB_SHOW_LOGS` with default value to `false`.
The previous behaviors was, always show gorm logs
=> Add config to show or not gorm logs

CHANGELOG.md, pkg/server/app/app.go, pkg/server/app/app_test.go, pkg/server/app/errors.go, pkg/server/k8s/errors.go
To return a friendly error message when an invalid app name is used
in app create method
=> Change validation of error on namespace create

CHANGELOG.md, pkg/server/app/app.go, pkg/server/app/app_test.go, pkg/server/app/errors.go
Return a friendly error message when the env var name is invalid.
=> Better error handling in app env-set

CHANGELOG.md, pkg/server/k8s/converters.go, pkg/server/k8s/converters_test.go, pkg/server/spec/pod.go
A Pod has one container (for now) and volumes. A container has volume
mounts.
=> Refactor specs to be more in line with k8s concepts

.travis.yml
Related to issue https://github.com/goreleaser/goreleaser/issues/588
and follow the [official docs](https://goreleaser.com/\#continuous_integration.travis)
=> Change command to get and install goreleaser on travis script

pkg/server/k8s/converters.go, pkg/server/k8s/converters_test.go, pkg/server/spec/cronjob.go
The default is 3 for both successful and failed jobs.
=> Add default limit to the cronjob jobs history

pkg/server/deploy/deploy.go, pkg/server/deploy/deploy_test.go, pkg/server/deploy/errors.go
We return a schedule not found message to the client.
=> Fix cronjob creation when the schedule is missing

CHANGELOG.md, README.md, pkg/server/app/app.go, pkg/server/app/app_test.go, pkg/server/app/cronjob.go, pkg/server/app/cronjob_test.go, pkg/server/app/models.go, pkg/server/deploy/deploy.go, pkg/server/deploy/deploy_test.go
This change allows users to create more than one cron job per code base
(ex. `cron`, `cron-a`, `cronjob`, `cron-b`, etc)
=> Check if an app is a CronJob by `cron` prefix

CHANGELOG.md, pkg/server/spec/container.go, pkg/server/spec/container_test.go
=> Protect nginx vars from being interpreted as env vars

pkg/server/spec/container.go, pkg/server/spec/container_test.go
The func and the test uses maps and we cannot guarantee the order of envs
=> Fix nginx cmd args tests on spec pkg

CHANGELOG.md, pkg/server/deploy/deploy.go, pkg/server/deploy/deploy_test.go, pkg/server/exec/errors.go, pkg/server/exec/exec.go, pkg/server/exec/exec_test.go, pkg/server/k8s/client.go
This change prevents to successfully deploy message when waiting
time reach the timeout of wait of PodRun func
Fixes #464
=> Return `ErrTimeout` on pod run when `wait.PollImmediate` return timeout error

CHANGELOG.md, pkg/client/cmd/deploy.go
- warn about nginx and secrets limitations
- ask for confirmation (can be disabled with --no-input)
- show the app name, revision and target cluster
=> Improve `deploy rollback` usability

CHANGELOG.md, pkg/server/deploy/deploy.go, pkg/server/deploy/deploy_test.go, pkg/server/k8s/client.go
Return an error if the former is stalled. Fixes #463.
=> Monitor the rolling update after the deploy

FAQ.md
This parameter will hide the nginx version from showing when any status code page from nginx is shown. 
Many ways of hacking nginx are based in just searching by nginx and the version and this would make more difficult to hack it.
=> Add server_tokens off param to nginx default conf

CHANGELOG.md, pkg/client/cmd/config.go
The `rm-cluster` command receives the cluster name as the parameter, removes
it from the map variable and rewrites the config file with the remaining
clusters.
Closing #504
=> Add rm-cluster command to remove a cluster config

CHANGELOG.md, pkg/server/exec/handlers.go, pkg/server/exec/handlers_test.go, pkg/server/server.go
Use a keepalive message. A little copying is better than the wrong
abstraction.
=> Fix long running exec commands

CHANGELOG.md, pkg/server/k8s/client.go, pkg/server/k8s/converters.go, pkg/server/k8s/converters_test.go
Adapt the kubectl code to get the state, restarts and ready fields
correctly. Fixes #531.
=> Fix `app info` command output

CHANGELOG.md, pkg/client/cmd/app.go, pkg/client/cmd/exec.go, pkg/client/cmd/service.go, pkg/client/errors.go, pkg/client/errors_test.go
Since teresa-client user don't need to know how things works, i think that a better error message can help then in day-by-day usage.
Some examples of why i think that can be useful:
- A better message, with explicit instructions to retry **can** save some time.
- A message that have the error, not the cluster configuration, can be helpful to find some real problem.
Here has my proposal changes in use. This was a try to get app info when has no connection to cluster:
**before:**
```
$ teresa app info myapp
Error connecting to server: cluster.address.youalreadyknow:666
```
**after:**
```
$ ./teresa app info myapp
A connection error occour before you command run.
Please, try again.
Error details: context deadline exceeded
```
=> [Proposal] Improve connection error messages

CHANGELOG.md, pkg/server/database/models.go
Remove defaults from the base model, it turns out that gorm handles the
fields CreatedAt and UpdatedAt automatically by convention.
=> Fix database initial migration on mysql 5.7

CHANGELOG.md, FAQ.md, pkg/server/app/app.go, pkg/server/app/models.go, pkg/server/build/build.go, pkg/server/deploy/deploy.go, pkg/server/deploy/deploy_test.go, pkg/server/spec/runner.go
A process type is web like if it has the prefix `web`
(ex. `web`, `web-a`, `webapi`, etc)
=> Add support to create more than one web app per Procfile

pkg/server/k8s/converters.go, pkg/server/k8s/converters_test.go
The ingress specs created when `--reserve-static-ip` is supplied are wrong. It uses the same schema as the vhost spec:
```
spec:
rules:
- http:
paths:
- backend:
serviceName: test-app
servicePort: 80
path: /
```
However, there shouldn't be any paths on this annotation (as per [the Kubernetes docs on Single Service Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/#single-service-ingress)
```
spec:
backend:
serviceName: test-app
servicePort: 80
```
=> Fixed wrong spec for ingresses with static ip

pkg/server/exec/handlers.go
This allows us to audit which users have exec a command using `teresa exec`.
=> Added exec logs to Teresa server

helm/README.md, helm/chart/teresa/templates/deployment.yaml, helm/chart/teresa/values.yaml, pkg/server/deploy/deploy.go, pkg/server/deploy/deploy_test.go, pkg/server/deploy/handlers.go, pkg/server/k8s/client.go
This is needed, specially on GKE, where you might have two classes of ingress controllers but you are using only one (e.g. nginx ingress). 
This PR might affect existing ingresses though! However, it won't overwrite it to null.
=> Added ingress class annotation

.gitignore, CHANGELOG.md, helm/chart/teresa/templates/deployment.yaml, pkg/server/deploy/deploy.go, pkg/server/deploy/handlers.go, pkg/server/k8s/converters.go, pkg/server/spec/deploy.go, pkg/server/spec/deploy_test.go
https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html
Due to bad performance of ndots 5, we decided to set ndots 2 in every deploy and app creation
=> ndots 2 hardcoded

FAQ.md
With some tests this nginx configuration showed themselves be a lot more performatic and resilient, also fixed application errors with nginx in scales.
=> Add epoll and multi_accept in nginx default config examples in FAQ

CHANGELOG.md, pkg/server/app/app.go, pkg/server/app/app_test.go, pkg/server/deploy/deploy.go, pkg/server/deploy/deploy_test.go, pkg/server/k8s/client.go, pkg/server/k8s/converters.go, pkg/server/k8s/converters_test.go
When we were developing the Ingress support for GCE, we thought the Ingress spec had to be different. However, after testing the same spec we create for Vhost for a couple of months, we found out that there was no problem in using it.
=> This PR simplifies ingress
